### Get All Tasks

GET http://localhost:3000/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG4uZG9lIiwiaWF0IjoxNjUzNjE0MzA4LCJleHAiOjE2NTM2MTc5MDh9.jRCM7k18CSEnwaHNtDhtJh7kGSj8f2Zj93wpgGOIo-Q


### Get Tasks With Filters

GET http://localhost:3000/tasks?status=OPEN&search=room


### Create a Task

POST http://localhost:3000/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG4uZG9lIiwiaWF0IjoxNjUzOTU5NDE3LCJleHAiOjE2NTM5NjMwMTd9.NT1Ge-jeBnDwxscpNLS91WIdhKeboAikJ7Y1kwpEvQk
Content-Type: application/x-www-form-urlencoded

title=Clean My Room
&description=Lots o cleaning has to be done

### Get Task By Id

GET http://localhost:3000/tasks/03eed331-6bb9-4e75-9716-0327006576e6

### Delete Task By Id

DELETE http://localhost:3000/tasks/dbbfd131-eb12-45a1-9cce-216a744e4a13


### Update Task Status By Id

PATCH http://localhost:3000/tasks/dfe9c44a-415a-43bd-af3a-d661c1efa346/status
Content-Type: application/json

{
  "status": "IN_PROGRESS"
}

### SignUp

POST http://localhost:3000/auth/signup
Content-Type: application/x-www-form-urlencoded

username=john.doe
&password=SUperScretP4sww0!

### SignIn

POST http://localhost:3000/auth/signin
Content-Type: application/x-www-form-urlencoded

username=john.doe
&password=SUperScretP4sww0!


### Auth Guard Test
# POST http://localhost:3000/auth/test
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG4uZG9lIiwiaWF0IjoxNjUzNjE0MzA4LCJleHAiOjE2NTM2MTc5MDh9.jRCM7k18CSEnwaHNtDhtJh7kGSj8f2Zj93wpgGOIo-Q
