### Get All Tasks

GET http://localhost:3000/tasks

### Get Tasks With Filters

GET http://localhost:3000/tasks?status=OPEN&search=room


### Create a Task

POST http://localhost:3000/tasks
Content-Type: application/x-www-form-urlencoded

title=Clean My Room 3
&description=Lots o cleaning has to be done

### Get Task By Id

GET http://localhost:3000/tasks/03eed331-6bb9-4e75-9716-0327006576e6

### Delete Task By Id

DELETE http://localhost:3000/tasks/dbbfd131-eb12-45a1-9cce-216a744e4a13


### Update Task Status By Id

PATCH http://localhost:3000/tasks/dfe9c44a-415a-43bd-af3a-d661c1efa346/status
Content-Type: application/json

{
  "status": "IN_PROGRESS"
}

### SignUp

POST http://localhost:3000/auth/signup
Content-Type: application/x-www-form-urlencoded

username=john.doe2
&password=SUperScretP4sww0!
